version: '3.8'

services:

  #NGINX Server
  web:
    container_name: news-nginx
    hostname: newsaggregatorwebsrv
    image: nginx:latest
    restart: always
    ports:
      - 8089:80
    volumes:
      - ./backend/src:/public_html
      - ./backend/conf.d:/etc/nginx/conf.d
      - ./backend/logs/nginx:/var/log/nginx/
    depends_on:
      - php
   
      
  #PHP 
  php:
    container_name: news-php
    hostname: newsaggregatorphpsrv
    build: 
      context: ./php-fpm          
      dockerfile: Dockerfile    
    volumes:
      - ./backend/src:/public_html
      - ./backend/logs/php-fpm:/var/log/fpm-php.www.log
      #- ./php.ini:/usr/local/etc/
    expose:
      - 9000



  #redis
  # cache: 
  #   container_name: redis-server
  #   hostname: redisserversrv
  #   # build: 
  #   #   context: ./redis          # defines either a path to a directory containing a Dockerfile, or a url to a git repository
  #   #   dockerfile: Dockerfile
  #   image: redis:alpine
  #   restart: always  
  #   ports:
  #     - '6379:6379'
  #   volumes: 
  #     - ./redis/cache:/data
  #   command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81  



  #supervisor
  # supervisor:
  #   container_name: supervisor-server
  #   hostname: supervisorserversrv
  #   build: 
  #     context: ./supervisor          # defines either a path to a directory containing a Dockerfile, or a url to a git repository
  #     dockerfile: Dockerfile 
  #   restart: always  
  #   volumes: 
  #     - ../backend/src:/public_html
  #     - ./supervisor/cli/supervisor-init.sh:/usr/local/bin/supervisor-init.sh
  #     - ./supervisor/logs/supervisor.log:/etc/supervisor/logs/supervisord.log
  #   entrypoint: >
  #     sh -c "chmod 777 /usr/local/bin/supervisor-init.sh
  #     && exec /usr/bin/supervisord --nodaemon --configuration=/etc/supervisor/supervisord.conf
  #     && /usr/local/bin/supervisor-init.sh"  





  #Composer 
  composer:
        image: composer
        volumes:
            - ./backend/src:/public_html
        command: install


  #MySQL Database
  db:
    image: mysql:8.0
    container_name: news-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_DATABASE: news_aggregator_db
      MYSQL_USER: khayrul
      MYSQL_PASSWORD: root@123A
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./backend/mysql_db/data:/var/lib/mysql
    ports:
      - 3307:3306  


  # Frontend
  portal:
    container_name: news-portal
    hostname: newsaggregatorportalsrv
    build:
      context: ./frontend    
      dockerfile: Dockerfile                        
    restart: always
    environment:
      TZ: "Asia/Dhaka"
    ports: 
      - 8088:80
      


networks:
  default:
    name: newsnet
    external: true